name: Makefile CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0

      - name: Run test
        run: make test
