name: Makefile CI

on:
  push:
    branches: ['main', 'dev', 'prod', 'staging']
  pull_request:

jobs:
  pr_compile_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0

      - name: Run test
        run: make test

  build_push:
    needs: pr_compile_lint_test

    if: github.event.pull_request.merged == true || github.event.pull_request.commited == true

    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: build artifact
        uses: echo "building artifact"
